/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWealthRouteImport } from './routes/_app.wealth'
import { Route as AppToolsRouteImport } from './routes/_app.tools'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppMoneyRouteImport } from './routes/_app.money'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppToolsIndexRouteImport } from './routes/_app.tools.index'
import { Route as AppToolsFinancialCalculatorRouteImport } from './routes/_app.tools.financial-calculator'
import { Route as AppPlannerFireRouteImport } from './routes/_app.planner.fire'
import { Route as AppMoneyTransactionsRouteImport } from './routes/_app.money.transactions'
import { Route as AppDashboardNetworthRouteImport } from './routes/_app.dashboard.networth'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWealthRoute = AppWealthRouteImport.update({
  id: '/wealth',
  path: '/wealth',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsFinancialCalculatorRoute =
  AppToolsFinancialCalculatorRouteImport.update({
    id: '/financial-calculator',
    path: '/financial-calculator',
    getParentRoute: () => AppToolsRoute,
  } as any)
const AppPlannerFireRoute = AppPlannerFireRouteImport.update({
  id: '/fire',
  path: '/fire',
  getParentRoute: () => AppPlannerRoute,
} as any)
const AppMoneyTransactionsRoute = AppMoneyTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppMoneyRoute,
} as any)
const AppDashboardNetworthRoute = AppDashboardNetworthRouteImport.update({
  id: '/networth',
  path: '/networth',
  getParentRoute: () => AppDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/feedback': typeof AppFeedbackRoute
  '/money': typeof AppMoneyRouteWithChildren
  '/planner': typeof AppPlannerRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tools': typeof AppToolsRouteWithChildren
  '/wealth': typeof AppWealthRoute
  '/dashboard/networth': typeof AppDashboardNetworthRoute
  '/money/transactions': typeof AppMoneyTransactionsRoute
  '/planner/fire': typeof AppPlannerFireRoute
  '/tools/financial-calculator': typeof AppToolsFinancialCalculatorRoute
  '/tools/': typeof AppToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/feedback': typeof AppFeedbackRoute
  '/money': typeof AppMoneyRouteWithChildren
  '/planner': typeof AppPlannerRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/wealth': typeof AppWealthRoute
  '/dashboard/networth': typeof AppDashboardNetworthRoute
  '/money/transactions': typeof AppMoneyTransactionsRoute
  '/planner/fire': typeof AppPlannerFireRoute
  '/tools/financial-calculator': typeof AppToolsFinancialCalculatorRoute
  '/tools': typeof AppToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/money': typeof AppMoneyRouteWithChildren
  '/_app/planner': typeof AppPlannerRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tools': typeof AppToolsRouteWithChildren
  '/_app/wealth': typeof AppWealthRoute
  '/_app/dashboard/networth': typeof AppDashboardNetworthRoute
  '/_app/money/transactions': typeof AppMoneyTransactionsRoute
  '/_app/planner/fire': typeof AppPlannerFireRoute
  '/_app/tools/financial-calculator': typeof AppToolsFinancialCalculatorRoute
  '/_app/tools/': typeof AppToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/feedback'
    | '/money'
    | '/planner'
    | '/settings'
    | '/tools'
    | '/wealth'
    | '/dashboard/networth'
    | '/money/transactions'
    | '/planner/fire'
    | '/tools/financial-calculator'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/feedback'
    | '/money'
    | '/planner'
    | '/settings'
    | '/wealth'
    | '/dashboard/networth'
    | '/money/transactions'
    | '/planner/fire'
    | '/tools/financial-calculator'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/money'
    | '/_app/planner'
    | '/_app/settings'
    | '/_app/tools'
    | '/_app/wealth'
    | '/_app/dashboard/networth'
    | '/_app/money/transactions'
    | '/_app/planner/fire'
    | '/_app/tools/financial-calculator'
    | '/_app/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wealth': {
      id: '/_app/wealth'
      path: '/wealth'
      fullPath: '/wealth'
      preLoaderRoute: typeof AppWealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money': {
      id: '/_app/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/tools/financial-calculator': {
      id: '/_app/tools/financial-calculator'
      path: '/financial-calculator'
      fullPath: '/tools/financial-calculator'
      preLoaderRoute: typeof AppToolsFinancialCalculatorRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/planner/fire': {
      id: '/_app/planner/fire'
      path: '/fire'
      fullPath: '/planner/fire'
      preLoaderRoute: typeof AppPlannerFireRouteImport
      parentRoute: typeof AppPlannerRoute
    }
    '/_app/money/transactions': {
      id: '/_app/money/transactions'
      path: '/transactions'
      fullPath: '/money/transactions'
      preLoaderRoute: typeof AppMoneyTransactionsRouteImport
      parentRoute: typeof AppMoneyRoute
    }
    '/_app/dashboard/networth': {
      id: '/_app/dashboard/networth'
      path: '/networth'
      fullPath: '/dashboard/networth'
      preLoaderRoute: typeof AppDashboardNetworthRouteImport
      parentRoute: typeof AppDashboardRoute
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardNetworthRoute: typeof AppDashboardNetworthRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardNetworthRoute: AppDashboardNetworthRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppMoneyRouteChildren {
  AppMoneyTransactionsRoute: typeof AppMoneyTransactionsRoute
}

const AppMoneyRouteChildren: AppMoneyRouteChildren = {
  AppMoneyTransactionsRoute: AppMoneyTransactionsRoute,
}

const AppMoneyRouteWithChildren = AppMoneyRoute._addFileChildren(
  AppMoneyRouteChildren,
)

interface AppPlannerRouteChildren {
  AppPlannerFireRoute: typeof AppPlannerFireRoute
}

const AppPlannerRouteChildren: AppPlannerRouteChildren = {
  AppPlannerFireRoute: AppPlannerFireRoute,
}

const AppPlannerRouteWithChildren = AppPlannerRoute._addFileChildren(
  AppPlannerRouteChildren,
)

interface AppToolsRouteChildren {
  AppToolsFinancialCalculatorRoute: typeof AppToolsFinancialCalculatorRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
}

const AppToolsRouteChildren: AppToolsRouteChildren = {
  AppToolsFinancialCalculatorRoute: AppToolsFinancialCalculatorRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
}

const AppToolsRouteWithChildren = AppToolsRoute._addFileChildren(
  AppToolsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppMoneyRoute: typeof AppMoneyRouteWithChildren
  AppPlannerRoute: typeof AppPlannerRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppToolsRoute: typeof AppToolsRouteWithChildren
  AppWealthRoute: typeof AppWealthRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppFeedbackRoute: AppFeedbackRoute,
  AppMoneyRoute: AppMoneyRouteWithChildren,
  AppPlannerRoute: AppPlannerRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppToolsRoute: AppToolsRouteWithChildren,
  AppWealthRoute: AppWealthRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
