/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsNewRouteImport } from './routes/_app.whats-new'
import { Route as AppWealthRouteImport } from './routes/_app.wealth'
import { Route as AppToolsRouteImport } from './routes/_app.tools'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMoneyRouteImport } from './routes/_app.money'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppToolsIndexRouteImport } from './routes/_app.tools.index'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppWealthAddInvestmentRouteImport } from './routes/_app.wealth_.add-investment'
import { Route as AppToolsFinancialCalculatorRouteImport } from './routes/_app.tools.financial-calculator'
import { Route as AppReportsIdRouteImport } from './routes/_app.reports.$id'
import { Route as AppMoneyTransactionsRouteImport } from './routes/_app.money.transactions'
import { Route as AppHoldingsSlugRouteImport } from './routes/_app.holdings.$slug'
import { Route as AppDashboardNetworthRouteImport } from './routes/_app.dashboard.networth'
import { Route as ApiPublicHooksReleaseNotesRouteImport } from './routes/api/public/hooks/release-notes'
import { Route as ApiPublicHooksNotificationCronRouteImport } from './routes/api/public/hooks/notification-cron'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsNewRoute = AppWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => AppRoute,
} as any)
const AppWealthRoute = AppWealthRouteImport.update({
  id: '/wealth',
  path: '/wealth',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppWealthAddInvestmentRoute = AppWealthAddInvestmentRouteImport.update({
  id: '/wealth_/add-investment',
  path: '/wealth/add-investment',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsFinancialCalculatorRoute =
  AppToolsFinancialCalculatorRouteImport.update({
    id: '/financial-calculator',
    path: '/financial-calculator',
    getParentRoute: () => AppToolsRoute,
  } as any)
const AppReportsIdRoute = AppReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyTransactionsRoute = AppMoneyTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppMoneyRoute,
} as any)
const AppHoldingsSlugRoute = AppHoldingsSlugRouteImport.update({
  id: '/holdings/$slug',
  path: '/holdings/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardNetworthRoute = AppDashboardNetworthRouteImport.update({
  id: '/networth',
  path: '/networth',
  getParentRoute: () => AppDashboardRoute,
} as any)
const ApiPublicHooksReleaseNotesRoute =
  ApiPublicHooksReleaseNotesRouteImport.update({
    id: '/api/public/hooks/release-notes',
    path: '/api/public/hooks/release-notes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotificationCronRoute =
  ApiPublicHooksNotificationCronRouteImport.update({
    id: '/api/public/hooks/notification-cron',
    path: '/api/public/hooks/notification-cron',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/feedback': typeof AppFeedbackRoute
  '/money': typeof AppMoneyRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/planner': typeof AppPlannerRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/tools': typeof AppToolsRouteWithChildren
  '/wealth': typeof AppWealthRoute
  '/whats-new': typeof AppWhatsNewRoute
  '/dashboard/networth': typeof AppDashboardNetworthRoute
  '/holdings/$slug': typeof AppHoldingsSlugRoute
  '/money/transactions': typeof AppMoneyTransactionsRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/tools/financial-calculator': typeof AppToolsFinancialCalculatorRoute
  '/wealth/add-investment': typeof AppWealthAddInvestmentRoute
  '/reports/': typeof AppReportsIndexRoute
  '/tools/': typeof AppToolsIndexRoute
  '/api/public/hooks/notification-cron': typeof ApiPublicHooksNotificationCronRoute
  '/api/public/hooks/release-notes': typeof ApiPublicHooksReleaseNotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/feedback': typeof AppFeedbackRoute
  '/money': typeof AppMoneyRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/planner': typeof AppPlannerRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/wealth': typeof AppWealthRoute
  '/whats-new': typeof AppWhatsNewRoute
  '/dashboard/networth': typeof AppDashboardNetworthRoute
  '/holdings/$slug': typeof AppHoldingsSlugRoute
  '/money/transactions': typeof AppMoneyTransactionsRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/tools/financial-calculator': typeof AppToolsFinancialCalculatorRoute
  '/wealth/add-investment': typeof AppWealthAddInvestmentRoute
  '/reports': typeof AppReportsIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/api/public/hooks/notification-cron': typeof ApiPublicHooksNotificationCronRoute
  '/api/public/hooks/release-notes': typeof ApiPublicHooksReleaseNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/money': typeof AppMoneyRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tools': typeof AppToolsRouteWithChildren
  '/_app/wealth': typeof AppWealthRoute
  '/_app/whats-new': typeof AppWhatsNewRoute
  '/_app/dashboard/networth': typeof AppDashboardNetworthRoute
  '/_app/holdings/$slug': typeof AppHoldingsSlugRoute
  '/_app/money/transactions': typeof AppMoneyTransactionsRoute
  '/_app/reports/$id': typeof AppReportsIdRoute
  '/_app/tools/financial-calculator': typeof AppToolsFinancialCalculatorRoute
  '/_app/wealth_/add-investment': typeof AppWealthAddInvestmentRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/api/public/hooks/notification-cron': typeof ApiPublicHooksNotificationCronRoute
  '/api/public/hooks/release-notes': typeof ApiPublicHooksReleaseNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/feedback'
    | '/money'
    | '/notifications'
    | '/planner'
    | '/profile'
    | '/settings'
    | '/tools'
    | '/wealth'
    | '/whats-new'
    | '/dashboard/networth'
    | '/holdings/$slug'
    | '/money/transactions'
    | '/reports/$id'
    | '/tools/financial-calculator'
    | '/wealth/add-investment'
    | '/reports/'
    | '/tools/'
    | '/api/public/hooks/notification-cron'
    | '/api/public/hooks/release-notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/feedback'
    | '/money'
    | '/notifications'
    | '/planner'
    | '/profile'
    | '/settings'
    | '/wealth'
    | '/whats-new'
    | '/dashboard/networth'
    | '/holdings/$slug'
    | '/money/transactions'
    | '/reports/$id'
    | '/tools/financial-calculator'
    | '/wealth/add-investment'
    | '/reports'
    | '/tools'
    | '/api/public/hooks/notification-cron'
    | '/api/public/hooks/release-notes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/money'
    | '/_app/notifications'
    | '/_app/planner'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/tools'
    | '/_app/wealth'
    | '/_app/whats-new'
    | '/_app/dashboard/networth'
    | '/_app/holdings/$slug'
    | '/_app/money/transactions'
    | '/_app/reports/$id'
    | '/_app/tools/financial-calculator'
    | '/_app/wealth_/add-investment'
    | '/_app/reports/'
    | '/_app/tools/'
    | '/api/public/hooks/notification-cron'
    | '/api/public/hooks/release-notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksNotificationCronRoute: typeof ApiPublicHooksNotificationCronRoute
  ApiPublicHooksReleaseNotesRoute: typeof ApiPublicHooksReleaseNotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whats-new': {
      id: '/_app/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof AppWhatsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wealth': {
      id: '/_app/wealth'
      path: '/wealth'
      fullPath: '/wealth'
      preLoaderRoute: typeof AppWealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money': {
      id: '/_app/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wealth_/add-investment': {
      id: '/_app/wealth_/add-investment'
      path: '/wealth/add-investment'
      fullPath: '/wealth/add-investment'
      preLoaderRoute: typeof AppWealthAddInvestmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/financial-calculator': {
      id: '/_app/tools/financial-calculator'
      path: '/financial-calculator'
      fullPath: '/tools/financial-calculator'
      preLoaderRoute: typeof AppToolsFinancialCalculatorRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/reports/$id': {
      id: '/_app/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AppReportsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money/transactions': {
      id: '/_app/money/transactions'
      path: '/transactions'
      fullPath: '/money/transactions'
      preLoaderRoute: typeof AppMoneyTransactionsRouteImport
      parentRoute: typeof AppMoneyRoute
    }
    '/_app/holdings/$slug': {
      id: '/_app/holdings/$slug'
      path: '/holdings/$slug'
      fullPath: '/holdings/$slug'
      preLoaderRoute: typeof AppHoldingsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/networth': {
      id: '/_app/dashboard/networth'
      path: '/networth'
      fullPath: '/dashboard/networth'
      preLoaderRoute: typeof AppDashboardNetworthRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/api/public/hooks/release-notes': {
      id: '/api/public/hooks/release-notes'
      path: '/api/public/hooks/release-notes'
      fullPath: '/api/public/hooks/release-notes'
      preLoaderRoute: typeof ApiPublicHooksReleaseNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notification-cron': {
      id: '/api/public/hooks/notification-cron'
      path: '/api/public/hooks/notification-cron'
      fullPath: '/api/public/hooks/notification-cron'
      preLoaderRoute: typeof ApiPublicHooksNotificationCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardNetworthRoute: typeof AppDashboardNetworthRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardNetworthRoute: AppDashboardNetworthRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppMoneyRouteChildren {
  AppMoneyTransactionsRoute: typeof AppMoneyTransactionsRoute
}

const AppMoneyRouteChildren: AppMoneyRouteChildren = {
  AppMoneyTransactionsRoute: AppMoneyTransactionsRoute,
}

const AppMoneyRouteWithChildren = AppMoneyRoute._addFileChildren(
  AppMoneyRouteChildren,
)

interface AppToolsRouteChildren {
  AppToolsFinancialCalculatorRoute: typeof AppToolsFinancialCalculatorRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
}

const AppToolsRouteChildren: AppToolsRouteChildren = {
  AppToolsFinancialCalculatorRoute: AppToolsFinancialCalculatorRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
}

const AppToolsRouteWithChildren = AppToolsRoute._addFileChildren(
  AppToolsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppMoneyRoute: typeof AppMoneyRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppToolsRoute: typeof AppToolsRouteWithChildren
  AppWealthRoute: typeof AppWealthRoute
  AppWhatsNewRoute: typeof AppWhatsNewRoute
  AppHoldingsSlugRoute: typeof AppHoldingsSlugRoute
  AppReportsIdRoute: typeof AppReportsIdRoute
  AppWealthAddInvestmentRoute: typeof AppWealthAddInvestmentRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppFeedbackRoute: AppFeedbackRoute,
  AppMoneyRoute: AppMoneyRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppToolsRoute: AppToolsRouteWithChildren,
  AppWealthRoute: AppWealthRoute,
  AppWhatsNewRoute: AppWhatsNewRoute,
  AppHoldingsSlugRoute: AppHoldingsSlugRoute,
  AppReportsIdRoute: AppReportsIdRoute,
  AppWealthAddInvestmentRoute: AppWealthAddInvestmentRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksNotificationCronRoute: ApiPublicHooksNotificationCronRoute,
  ApiPublicHooksReleaseNotesRoute: ApiPublicHooksReleaseNotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
